stages:
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache docker-cli docker-compose # Docker CLI와 Docker Compose 설치
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

test_front:
  stage: test
  script:
    - docker-compose -f docker-compose.yaml up -d wss-front
    - docker-compose -f docker-compose.yaml exec wss-front npm test
  only:
    - develop
    - master

test_back:
  stage: test
  script:
    - docker-compose -f docker-compose.yaml up -d wss-back
    - docker-compose -f docker-compose.yaml exec wss-back npm test
  only:
    - develop
    - master

test_db:
  stage: test
  script:
    - docker-compose -f docker-compose.yaml up -d wss-userdb wss-datadb
    - docker-compose -f docker-compose.yaml exec wss-userdb mysqlcheck --all-databases
    - docker-compose -f docker-compose.yaml exec wss-datadb mysqlcheck --all-databases
  only:
    - develop
    - master

deploy:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yaml up -d
  only:
    - master