stages:
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "" # TLS 인증서 디렉토리 비활성화

image: docker:latest

services:
  - name: docker:dind
    command: ["--tls=false", "--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock"]

before_script:
  - apk add --no-cache docker-cli docker-compose # Docker CLI와 Docker Compose 설치
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

test_front:
  stage: test
  script:
    - docker-compose -f docker-compose.yaml up -d wss-front
  only:
    - develop
    - master

test_back:
  stage: test
  script:
    - docker-compose -f docker-compose.yaml up -d wss-back
  only:
    - develop
    - master

test_db:
  stage: test
  script:
    - docker-compose -f docker-compose.yaml up -d wss-userdb wss-datadb
    - docker-compose -f docker-compose.yaml exec wss-userdb mysqlcheck --all-databases
    - docker-compose -f docker-compose.yaml exec wss-datadb mysqlcheck --all-databases
  only:
    - develop
    - master

deploy:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yaml up -d
  only:
    - master

test_docker:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker info