stages:
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

image: docker:latest

before_script:
  - apk add --no-cache docker-cli docker-compose
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - echo -e "MYSQL_ROOT_PASSWORD=testdb123\nMYSQL_DATABASE=testdb" > .env

test:
  stage: test
  script:
    - cd front/nginx/ssl
    - ls
    - chmod +x setup_ssl.sh
    - ./setup_ssl.sh
    - cd ~
    - export DOCKER_HOST=unix:///var/run/docker.sock
    - docker-compose -f docker-compose.yaml up -d
  only:
    - develop
    - master

deploy:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh $SSH_USER@$SSH_HOST 'cd FitUrRing && ./deploy.sh'
  only:
    - master