image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - deploy

before_script:
  - docker info
  - apk add --no-cache docker-compose

build:
  stage: build
  script:
    - docker-compose -f docker-compose.yaml build
  only:
    - develop
    - master

deploy:
  stage: deploy
  script:
    - echo "Deploying to server"
    - ./deploy.sh
  only:
    - develop
    - master